### ISSUE TITLE
Typography and spacing

### ISSUE THREAD

**Issue by soniaturcotte** [citizensadvice/design-system-testing#1]
### Global font color
Font color: #0C0C0C unless otherwise specified

### Headings, small screens, 0px - 768px 
Heading 1
Font size: 32px
Line height: 40px
Font weight: 700 

Heading 2
Font size: 24px
Line height: 30px
Font weight: 700 

Heading 3
Font size: 20px
Line height: 25px
Font weight: 700 

Heading 4
These will be used by specific components. The content designers will not be able to select these for use in content. 
Font size: 16px
Line height: 20px
Font weight: 700

### Headings, large screens, 768px and above
Heading 1
Font size: 40px
Line height: 48px
Font weight: 700 

Heading 2
Font size: 32px
Line height: 40px
Font weight: 700

Heading 3
Font size: 22.4px
Line height: 30px
Font weight: 700

Heading 4
These will be used by specific components. The content designers will not be able to select these for use in content. 
Font size: 18px
Line height: 24px
Font weight: 700

----

### Paragraphs, small screens, 0px - 768px 
Font size: 16px
Line height: 24px
Font weight: 400
Paragraph spacing: 24px

**Bold text**
Font weight: 700

### Paragraphs, large screens, 768px and above
Font size: 18px
Line height: 24px
Font weight: 400
Paragraph spacing: 24px

**Bold text**
Font weight: 700

----

### Lists (bullet and numbered), small screens, 0px - 768px 
Font size: 16px
Line height: 24px
Font weight: 400
Paragraph spacing: 28px

### Lists (bullet and numbered), large screens, 768px and above
Font size: 18px
Line height: 24px
Font weight: 400
Paragraph spacing: 28px

**Comment by soniaturcotte** [comment]
Design in progress here: https://www.figma.com/file/IZY9uqY9RPjhIUv8ol1qjf/Design-System-Experimentation?node-id=195%3A1

**Comment by shakiradamji** [comment]
Change font colour to a dark grey, change heading colour to match paragraph text and change header font weight to bold agreed in design community meeting on 30th January.
